### ISSUE TITLE
Allow SSH agent key management

### ISSUE THREAD

**Issue by ricardomaraschini** [replicatedhq/helmvm#49]
Today when deploying with `--multi-node` the user is forced to provide a path to the SSH key for remote accessing the node. We should allow that field to be empty so the SSH agent can try to figure out the key to access the node by itself. This seems to be supported by `k0sctl`:

```yaml
- role: worker
   ssh:
   address: 10.24.233.209
   user: crdant
```

We could add an option to the SSH key selection that reads: `(leave blank to use SSH agent)`. Upon selecting this HelmVM will remove the key path section from the configuration.
